"""
REF-06 equivalence gate: bit-identical comparison of refactored pipeline output
against pre-change reference data.

Every test uses np.array_equal (strict bit-identical), never np.allclose.
Reference data was generated by Plan 03-01 Task 1 before any config/validation
changes.  If any test fails, the refactored code has introduced a behavioral
change -- which violates the Part A boundary rule.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_HERE = Path(__file__).resolve().parent
REFERENCE_DIR = _HERE / "reference"
SAMPLE_SCENE_DIR = _HERE.parent / "samples" / "010101"

_SKIP_NO_SCENE = pytest.mark.skipif(
    not (SAMPLE_SCENE_DIR / "coord.npy").exists(),
    reason="Sample scene 010101 not on disk",
)
_SKIP_NO_REF = pytest.mark.skipif(
    not REFERENCE_DIR.exists() or not (REFERENCE_DIR / "supports.npz").exists(),
    reason="Reference data not generated -- run Plan 03-01 Task 1 first",
)

pytestmark = [_SKIP_NO_SCENE, _SKIP_NO_REF]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _assert_npz_identical(ref_path: Path, actual: dict, label: str) -> None:
    """Assert every field in a reference NPZ matches the actual dict."""
    ref = np.load(ref_path)
    ref_keys = sorted(ref.files)
    actual_keys = sorted(actual.keys())
    assert ref_keys == actual_keys, (
        f"{label}: key mismatch -- ref={ref_keys}, actual={actual_keys}"
    )
    for key in ref_keys:
        r, a = ref[key], actual[key]
        if not np.array_equal(r, a):
            diff_idx = np.where(r != a)
            sample = tuple(idx[:5] for idx in diff_idx) if diff_idx[0].size else ()
            pytest.fail(
                f"{label}[{key}]: not bit-identical\n"
                f"  ref shape={r.shape} dtype={r.dtype}\n"
                f"  actual shape={a.shape} dtype={a.dtype}\n"
                f"  first diffs at: {sample}\n"
                f"  max |diff|={np.max(np.abs(r.astype(float) - a.astype(float)))}"
            )


def _assert_npy_identical(ref_path: Path, actual: np.ndarray, label: str) -> None:
    """Assert a reference .npy array matches the actual array."""
    ref = np.load(ref_path)
    if not np.array_equal(ref, actual):
        diff_idx = np.where(ref != actual)
        sample = tuple(idx[:5] for idx in diff_idx) if diff_idx[0].size else ()
        pytest.fail(
            f"{label}: not bit-identical\n"
            f"  ref shape={ref.shape} dtype={ref.dtype}\n"
            f"  actual shape={actual.shape} dtype={actual.dtype}\n"
            f"  first diffs at: {sample}\n"
            f"  max |diff|={np.max(np.abs(ref.astype(float) - actual.astype(float)))}"
        )


# ---------------------------------------------------------------------------
# Module-scoped fixtures: run pipeline once, reuse across tests
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def refactored_stage1(sample_scene_dir):
    """Run Stage 1 with default Stage1Config on scene 010101."""
    from core.config import Stage1Config
    from core.boundary_centers_core import build_boundary_centers
    from utils.stage_io import load_scene

    cfg = Stage1Config()
    scene = load_scene(sample_scene_dir)
    _, payload, _ = build_boundary_centers(
        scene=scene,
        k=cfg.k,
        min_cross_ratio=cfg.min_cross_ratio,
        min_side_points=cfg.min_side_points,
        ignore_index=cfg.ignore_index,
    )
    return payload


@pytest.fixture(scope="module")
def refactored_stage2(refactored_stage1):
    """Run Stage 2 with default Stage2Config."""
    from core.config import Stage2Config
    from core.local_clusters_core import cluster_boundary_centers

    cfg = Stage2Config()
    payload, _ = cluster_boundary_centers(
        boundary_centers=refactored_stage1,
        eps=cfg.eps,
        min_samples=cfg.min_samples,
        denoise_knn=cfg.denoise_knn,
        sparse_distance_ratio=cfg.sparse_distance_ratio,
        sparse_mad_scale=cfg.sparse_mad_scale,
    )
    return payload


@pytest.fixture(scope="module")
def refactored_stage3(refactored_stage1, refactored_stage2):
    """Run Stage 3 with default Stage3Config."""
    from core.config import Stage3Config
    from core.supports_core import build_supports_payload

    cfg = Stage3Config()
    payload, _, _ = build_supports_payload(
        boundary_centers=refactored_stage1,
        local_clusters=refactored_stage2,
        params=cfg.to_runtime_dict(),
    )
    return payload


@pytest.fixture(scope="module")
def refactored_stage4(sample_scene_dir, refactored_stage3):
    """Run Stage 4 with default Stage4Config."""
    from core.config import Stage4Config
    from core.pointwise_core import build_pointwise_edge_supervision
    from utils.stage_io import load_scene

    cfg = Stage4Config()
    scene = load_scene(sample_scene_dir)
    payload, _ = build_pointwise_edge_supervision(
        scene=scene,
        supports=refactored_stage3,
        support_radius=cfg.support_radius,
        ignore_index=cfg.ignore_index,
    )
    return payload


# ---------------------------------------------------------------------------
# Stage 1: boundary centers
# ---------------------------------------------------------------------------


def test_stage1_boundary_centers_identical(refactored_stage1, reference_dir):
    _assert_npz_identical(
        reference_dir / "boundary_centers.npz",
        refactored_stage1,
        "Stage 1 boundary_centers",
    )


# ---------------------------------------------------------------------------
# Stage 2: local clusters
# ---------------------------------------------------------------------------


def test_stage2_local_clusters_identical(refactored_stage2, reference_dir):
    _assert_npz_identical(
        reference_dir / "local_clusters.npz",
        refactored_stage2,
        "Stage 2 local_clusters",
    )


# ---------------------------------------------------------------------------
# Stage 3: supports
# ---------------------------------------------------------------------------


def test_stage3_supports_identical(refactored_stage3, reference_dir):
    _assert_npz_identical(
        reference_dir / "supports.npz",
        refactored_stage3,
        "Stage 3 supports",
    )


# ---------------------------------------------------------------------------
# Stage 4: pointwise edge supervision
# ---------------------------------------------------------------------------


def test_stage4_edge_dist_identical(refactored_stage4, reference_dir):
    _assert_npy_identical(
        reference_dir / "edge_dist.npy",
        refactored_stage4["edge_dist"],
        "Stage 4 edge_dist",
    )


def test_stage4_edge_dir_identical(refactored_stage4, reference_dir):
    _assert_npy_identical(
        reference_dir / "edge_dir.npy",
        refactored_stage4["edge_dir"],
        "Stage 4 edge_dir",
    )


def test_stage4_edge_valid_identical(refactored_stage4, reference_dir):
    _assert_npy_identical(
        reference_dir / "edge_valid.npy",
        refactored_stage4["edge_valid"],
        "Stage 4 edge_valid",
    )


def test_stage4_edge_support_id_identical(refactored_stage4, reference_dir):
    _assert_npy_identical(
        reference_dir / "edge_support_id.npy",
        refactored_stage4["edge_support_id"],
        "Stage 4 edge_support_id",
    )


# ---------------------------------------------------------------------------
# Cross-check: validation hooks pass on refactored output
# ---------------------------------------------------------------------------


def test_validation_passes_on_refactored_output(
    refactored_stage1,
    refactored_stage2,
    refactored_stage3,
    refactored_stage4,
    sample_scene_dir,
):
    from core.validation import (
        validate_boundary_centers,
        validate_local_clusters,
        validate_supports,
        validate_edge_supervision,
    )
    from utils.stage_io import load_scene

    validate_boundary_centers(refactored_stage1)
    validate_local_clusters(
        refactored_stage2,
        num_boundary_centers=refactored_stage1["center_coord"].shape[0],
    )
    validate_supports(refactored_stage3)
    scene = load_scene(sample_scene_dir)
    validate_edge_supervision(refactored_stage4, num_scene_points=scene["coord"].shape[0])


# ---------------------------------------------------------------------------
# In-memory path: Stages 1→2→3 in sequence matches per-stage results
# ---------------------------------------------------------------------------


def test_inmemory_path_matches_perstage(sample_scene_dir, refactored_stage3):
    """Run Stages 1→2→3 in-memory (build_support_dataset_v3 pattern) and
    compare Stage 3 output against the per-stage fixture result."""
    from core.config import Stage1Config, Stage2Config, Stage3Config
    from core.boundary_centers_core import build_boundary_centers
    from core.local_clusters_core import cluster_boundary_centers
    from core.supports_core import build_supports_payload
    from utils.stage_io import load_scene

    cfg1 = Stage1Config()
    cfg2 = Stage2Config()
    cfg3 = Stage3Config()

    scene = load_scene(sample_scene_dir)
    _, bc_payload, _ = build_boundary_centers(
        scene=scene,
        k=cfg1.k,
        min_cross_ratio=cfg1.min_cross_ratio,
        min_side_points=cfg1.min_side_points,
        ignore_index=cfg1.ignore_index,
    )
    lc_payload, _ = cluster_boundary_centers(
        boundary_centers=bc_payload,
        eps=cfg2.eps,
        min_samples=cfg2.min_samples,
        denoise_knn=cfg2.denoise_knn,
        sparse_distance_ratio=cfg2.sparse_distance_ratio,
        sparse_mad_scale=cfg2.sparse_mad_scale,
    )
    sup_payload, _, _ = build_supports_payload(
        boundary_centers=bc_payload,
        local_clusters=lc_payload,
        params=cfg3.to_runtime_dict(),
    )

    # Compare every field in supports payload
    ref_keys = sorted(refactored_stage3.keys())
    mem_keys = sorted(sup_payload.keys())
    assert ref_keys == mem_keys, f"Key mismatch: per-stage={ref_keys}, in-memory={mem_keys}"
    for key in ref_keys:
        assert np.array_equal(refactored_stage3[key], sup_payload[key]), (
            f"In-memory path differs from per-stage at supports[{key}]"
        )
