from __future__ import annotations

from pathlib import Path

import numpy as np


def load_scene(scene_dir: Path, with_optional: bool = True) -> dict:
    """Load one scene with v2-compatible inputs."""
    coord = np.load(scene_dir / "coord.npy").astype(np.float32)
    segment = np.load(scene_dir / "segment.npy").astype(np.int32).reshape(-1)

    normal = None
    color = None
    if with_optional:
        normal_path = scene_dir / "normal.npy"
        color_path = scene_dir / "color.npy"
        normal = np.load(normal_path).astype(np.float32) if normal_path.exists() else None
        color = np.load(color_path).astype(np.uint8) if color_path.exists() else None

    if coord.ndim != 2 or coord.shape[1] != 3:
        raise ValueError(f"coord.npy shape invalid: {coord.shape}")
    if segment.shape[0] != coord.shape[0]:
        raise ValueError(f"segment count mismatch: {segment.shape[0]} vs {coord.shape[0]}")
    if normal is not None and normal.shape != coord.shape:
        raise ValueError(f"normal.npy shape invalid: {normal.shape}")
    if color is not None and color.shape != coord.shape:
        raise ValueError(f"color.npy shape invalid: {color.shape}")

    return {
        "coord": coord,
        "segment": segment,
        "normal": normal,
        "color": color,
    }


def load_boundary_centers(input_dir: Path) -> dict:
    """Load boundary centers generated by bf_edge_v3."""
    payload = np.load(input_dir / "boundary_centers.npz")
    center_coord = payload["center_coord"].astype(np.float32)
    center_tangent = payload["center_tangent"].astype(np.float32)
    semantic_pair = payload["semantic_pair"].astype(np.int32)
    confidence = payload["confidence"].astype(np.float32)

    if center_coord.ndim != 2 or center_coord.shape[1] != 3:
        raise ValueError(f"center_coord shape invalid: {center_coord.shape}")
    if center_tangent.shape != center_coord.shape:
        raise ValueError(f"center_tangent shape invalid: {center_tangent.shape}")
    if semantic_pair.ndim != 2 or semantic_pair.shape[1] != 2:
        raise ValueError(f"semantic_pair shape invalid: {semantic_pair.shape}")
    if confidence.ndim != 1 or confidence.shape[0] != center_coord.shape[0]:
        raise ValueError("confidence count mismatch")

    result = {
        "center_coord": center_coord,
        "center_tangent": center_tangent,
        "semantic_pair": semantic_pair,
        "confidence": confidence,
    }
    if "center_normal" in payload.files:
        center_normal = payload["center_normal"].astype(np.float32)
        if center_normal.shape != center_coord.shape:
            raise ValueError(f"center_normal shape invalid: {center_normal.shape}")
        result["center_normal"] = center_normal
    if "source_point_index" in payload.files:
        source_point_index = payload["source_point_index"].astype(np.int32)
        if source_point_index.ndim != 1 or source_point_index.shape[0] != center_coord.shape[0]:
            raise ValueError("source_point_index count mismatch")
        result["source_point_index"] = source_point_index
    return result


def load_local_clusters(input_dir: Path) -> dict:
    """Load local clusters from bf_edge_v3.

    Post-Phase-4: cluster_trigger_flag is no longer produced or required.
    """
    payload = np.load(input_dir / "local_clusters.npz")
    center_index = payload["center_index"].astype(np.int32)
    cluster_id = payload["cluster_id"].astype(np.int32)
    semantic_pair = payload["semantic_pair"].astype(np.int32)
    cluster_size = payload["cluster_size"].astype(np.int32)
    cluster_centroid = payload["cluster_centroid"].astype(np.float32)

    if center_index.ndim != 1:
        raise ValueError(f"center_index shape invalid: {center_index.shape}")
    if cluster_id.ndim != 1 or cluster_id.shape[0] != center_index.shape[0]:
        raise ValueError("cluster_id shape/count mismatch")
    if semantic_pair.ndim != 2 or semantic_pair.shape[1] != 2:
        raise ValueError(f"semantic_pair shape invalid: {semantic_pair.shape}")
    if cluster_size.ndim != 1 or cluster_centroid.ndim != 2:
        raise ValueError("cluster_size or cluster_centroid shape invalid")
    if cluster_centroid.shape[1] != 3:
        raise ValueError(f"cluster_centroid shape invalid: {cluster_centroid.shape}")
    if not (
        semantic_pair.shape[0]
        == cluster_size.shape[0]
        == cluster_centroid.shape[0]
    ):
        raise ValueError("cluster-level field length mismatch")

    return {
        "center_index": center_index,
        "cluster_id": cluster_id,
        "semantic_pair": semantic_pair,
        "cluster_size": cluster_size,
        "cluster_centroid": cluster_centroid,
    }


def contains_stage_input(path: Path, required_files: tuple[str, ...]) -> bool:
    """Check whether a directory contains the required stage inputs."""
    return path.is_dir() and all((path / name).exists() for name in required_files)


def collect_stage_tasks(
    input_path: Path,
    output_path: Path | None,
    stage_file: str,
    required_files: tuple[str, ...],
) -> list[tuple[Path, Path]]:
    """Collect single-scene or batch tasks."""
    if contains_stage_input(input_path, required_files):
        return [(input_path, output_path if output_path is not None else input_path)]

    if not input_path.is_dir():
        return []

    input_dirs = sorted({p.parent for p in input_path.rglob(stage_file)})
    tasks = []
    for in_dir in input_dirs:
        if not all((in_dir / name).exists() for name in required_files):
            continue
        out_dir = in_dir if output_path is None else output_path / in_dir.relative_to(input_path)
        tasks.append((in_dir, out_dir))
    return tasks
